language: node_js
# nodejs版本
node_js:
  - "12"

# Travis-CI Caching
cache:
  directories:
    - node_modules

before_install:
  - node -v
  - npm -v
  - git branch

# S: Build Lifecycle
install:
  - npm install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build

# E: Build LifeCycle

branches:
  only:
    - master
env:
  global:
    # 我将其添加到了travis-ci的环境变量中

after_success:
  - ssh ./deploy.sh

after_script:
