language: node_js
# nodejs版本
node_js:
  - "12"

# Travis-CI Caching
cache:
  directories:
    - node_modules

before_install:
  - node -v
  - npm -v
  - git branch

# S: Build Lifecycle
install:
  - npm install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build

after_script:
  - echo "正在压缩, 请稍后..."
  - cp ./build ./server
  - tar -zcvf react-hooks-todolist.tar.gz ./server ./README.md ./build_production.sh

  - echo "上传中..."

  - sshpass -p ${password} scp ./react-hooks-todolist.tar.gz  ${user}@${host}:/home/quzhanxiang/react-hooks-todolist/
  - sshpass -p ${password} ssh ${user}@${host} "cd /home/quzhanxiang/react-hooks-todolist/ && tar -xzvf react-hooks-todolist.tar.gz && bash build_production.sh"
# E: Build LifeCycle

branches:
  only:
    - master
env:
  global:
    # 我将其添加到了travis-ci的环境变量中
